### ISSUE TITLE
UnicodeDecodeError on localized error messages in Windows

### ISSUE THREAD

**Issue by bjourne** [jakubroztocil/httpie#119]
I'm getting a socket-related error on Windows when the host can't be connected to:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\http-script.py", line 8, in <module>
    load_entry_point('httpie==0.3.1', 'console_scripts', 'http')()
  File "C:\Python27\lib\site-packages\httpie\core.py", line 120, in main
    error('%s: %s', type(e).__name__, str(e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 33: ordinal not in range(128)
```

On Windows, error messages relating to sockets are localized so `str(e)` is wrong and the text should be in unicode.

**Comment by jakubroztocil** [comment]
This has most likely been resolved by now.
