### ISSUE TITLE
Does not work pip install httpie in OpenBSD with python 3

### ISSUE THREAD

**Issue by TeeBSD** [jakubroztocil/httpie#149]
$ pip install httpie
Downloading/unpacking httpie
  Downloading httpie-0.6.0.tar.gz (63kB): 63kB downloaded
  Running setup.py egg_info for package httpie

Exception:
Traceback (most recent call last):
  File "/home/user/opt/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/home/user/opt/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/user/opt/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/req.py", line 1062, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/home/user/opt/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/req.py", line 371, in assert_source_matches_version
    version = self.installed_version
  File "/home/user/opt/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/req.py", line 367, in installed_version
    return self.pkg_info()['version']
  File "/home/user/opt/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/req.py", line 334, in pkg_info
    data = self.egg_info_data('PKG-INFO')
  File "/home/user/opt/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/req.py", line 274, in egg_info_data
    data = fp.read()
  File "/home/user/opt/lib/python3.3/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6047: ordinal not in range(128)

**Comment by TeeBSD** [comment]
Same error at Debian 7.

Downloading/unpacking httpie
  Downloading httpie-0.9.0.tar.gz (87Kb): 87Kb downloaded
  Running setup.py egg_info for package httpie

Downloading/unpacking requests>=2.3.0 (from httpie)
  Downloading requests-2.5.1.tar.gz (443Kb): 443Kb downloaded
  Running setup.py egg_info for package requests

Exception:
Traceback (most recent call last):
  File "/home/duchbeguice/p3k/lib/python3.2/site-packages/pip-1.1-py3.2.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/duchbeguice/p3k/lib/python3.2/site-packages/pip-1.1-py3.2.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/duchbeguice/p3k/lib/python3.2/site-packages/pip-1.1-py3.2.egg/pip/req.py", line 1014, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/home/duchbeguice/p3k/lib/python3.2/site-packages/pip-1.1-py3.2.egg/pip/req.py", line 359, in assert_source_matches_version
    version = self.installed_version
  File "/home/duchbeguice/p3k/lib/python3.2/site-packages/pip-1.1-py3.2.egg/pip/req.py", line 351, in installed_version
    return self.pkg_info()['version']
  File "/home/duchbeguice/p3k/lib/python3.2/site-packages/pip-1.1-py3.2.egg/pip/req.py", line 318, in pkg_info
    data = self.egg_info_data('PKG-INFO')
  File "/home/duchbeguice/p3k/lib/python3.2/site-packages/pip-1.1-py3.2.egg/pip/req.py", line 261, in egg_info_data
    data = fp.read()
  File "/home/duchbeguice/p3k/lib/python3.2/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8161: ordinal not in range(128)

Storing complete log in /home/duchbeguice/.pip/pip.log
