### ISSUE TITLE
Conditional requirements are broken with wheel

### ISSUE THREAD

**Issue by Jayin** [jakubroztocil/httpie#227]
in win7

```shell
C:\Users\Lenovo>pip install --upgrade httpie
Requirement already up-to-date: httpie in c:\python27\lib\site-packages
Cleaning up...

C:\Users\Lenovo>http httpie.org
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\http.exe\__main__.py", line 5, in <module>
  File "C:\Python27\lib\site-packages\httpie\__main__.py", line 6, in <module>
    from .core import main
  File "C:\Python27\lib\site-packages\httpie\core.py", line 23, in <module>
    from .downloads import Download
  File "C:\Python27\lib\site-packages\httpie\downloads.py", line 15, in <module>

    from .output import RawStream
  File "C:\Python27\lib\site-packages\httpie\output.py", line 19, in <module>
    from .models import HTTPRequest, HTTPResponse, Environment
  File "C:\Python27\lib\site-packages\httpie\models.py", line 8, in <module>
    class Environment(object):
  File "C:\Python27\lib\site-packages\httpie\models.py", line 34, in Environment

    from colorama.initialise import wrap_stream
ImportError: No module named colorama.initialise

```

**Comment by jakubroztocil** [comment]
This should be fixed in HTTPie v0.9.0. See:

https://github.com/jakubroztocil/httpie/issues/255#issuecomment-72316343
