### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by jakubroztocil** [jakubroztocil/httpie#298]
http://hyper.readthedocs.org/en/latest/quickstart.html#requests-integration

https://github.com/Lukasa/hyper/pull/82#issuecomment-72364932

**Comment by jakubroztocil** [comment]
https://github.com/jakubroztocil/httpie-http2

**Comment by Lukasa** [comment]
:cake:

**Comment by Yamakaky** [comment]
Any plan to merge it ?

**Comment by sigmavirus24** [comment]
@Yamakaky it's a plugin that you can install separately. What needs merging?

**Comment by Yamakaky** [comment]
It would be easier if it was a builtin. HTTP/2 is the future of HTTP, it would be great if it was supported by this great utility.

**Comment by bfred-it** [comment]
Also it's not on homebrew and after `pip install -U httpie httpie-http2`, running httpie gives me this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/http", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/httpie/core.py", line 183, in main
    plugin_manager.load_installed_plugins()
  File "/usr/local/lib/python2.7/site-packages/httpie/plugins/manager.py", line 33, in load_installed_plugins
    plugin = entry_point.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2368, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2385, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 835, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyOpenSSL 0.14 (/usr/local/lib/python2.7/site-packages), Requirement.parse('pyOpenSSL>=0.15'), set(['hyper']))
```

**Comment by Depado** [comment]
I wish HTTPie could also support HTTP/2, that would be awesome 👍

**Comment by maximbaz** [comment]
I think it's time to raise this topic again, I created a new issue #692 and listed all the reasons I could think of for merging the plugin into the `httpie` itself.
