### ISSUE TITLE
ModuleNotFoundError: No module named 'enum'

### ISSUE THREAD

**Issue by mahiuchun** [jakubroztocil/httpie#580]
I install Homebrew at $HOME/homebrew.
```bash
$ brew install httpie
$ http --debug
```
```
Traceback (most recent call last):
  File "/Users/hillma/homebrew/bin/http", line 4, in <module>
    import re
  File "/Users/hillma/homebrew/Cellar/httpie/0.9.9/libexec/lib/python3.6/re.py", line 122, in >><module>
    import enum
ModuleNotFoundError: No module named 'enum'
```

**Comment by iansinnott** [comment]
I'm running into the same issue, although I don't have it on another system where homebrew is installed globally. Perhaps its an issue with installing homebrew to your own users folder?

I still haven't solved this issue either. Any help would be much appreciated!

**Comment by jakubroztocil** [comment]
@mahiuchun This is pretty strange. 

The path shown in the traceback indicates that you're correctly on Python 3.6. 

The  built-in `re` module depends on `enum` but cannot find it — but it normally sits right next to it in the same folder.

So the fact that it cannot be found could mean that the Python installation is incomplete, or that the custom location breaks things. The later can probably be ruled out since @iansinnott has the same issue on a global installation.

The `enum` module has been added in Python 3.4, so the error could also mean that there's some wild `PYTHONPATH` manipulation and Python is trying to import it from a 2.7.x installation. Also unlikely, though.

Would you please post the output of the following commands, @mahiuchun?

```
ls -l /Users/hillma/homebrew/Cellar/httpie/0.9.9/libexec/lib/python3.6/
```

```
cat /Users/hillma/homebrew/bin/http
```

**Comment by jakubroztocil** [comment]
And also:
`/Users/hillma/homebrew/Cellar/httpie/0.9.9/libexec/bin/python3.6 -c 'import sys; from pprint import pprint; pprint(sys.path); import enum; print(enum)'`

**Comment by mahiuchun** [comment]
```
~$ ls -l /Users/hillma/homebrew/Cellar/httpie/0.9.9/libexec/lib/python3.6/
total 456
lrwxr-xr-x   1 hillma  eng     98 Dec  8 15:24 __future__.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/__future__.py
drwxr-xr-x  14 hillma  eng    476 May  1 10:40 __pycache__
lrwxr-xr-x   1 hillma  eng     99 Dec  8 15:24 _bootlocale.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_bootlocale.py
lrwxr-xr-x   1 hillma  eng    104 Dec  8 15:24 _collections_abc.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_collections_abc.py
lrwxr-xr-x   1 hillma  eng    101 Dec  8 15:24 _dummy_thread.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_dummy_thread.py
lrwxr-xr-x   1 hillma  eng     99 Dec  8 15:24 _weakrefset.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_weakrefset.py
lrwxr-xr-x   1 hillma  eng     91 Dec  8 15:24 abc.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 base64.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/base64.py
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 bisect.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bisect.py
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 codecs.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py
lrwxr-xr-x   1 hillma  eng     96 Dec  8 15:24 collections -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/collections
lrwxr-xr-x   1 hillma  eng    103 Dec  8 15:24 config-3.6m-darwin -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin
lrwxr-xr-x   1 hillma  eng     92 Dec  8 15:24 copy.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py
lrwxr-xr-x   1 hillma  eng     95 Dec  8 15:24 copyreg.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copyreg.py
drwxr-xr-x   5 hillma  eng    170 Dec  8 15:24 distutils
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 encodings -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings
lrwxr-xr-x   1 hillma  eng     95 Dec  8 15:24 fnmatch.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fnmatch.py
lrwxr-xr-x   1 hillma  eng     97 Dec  8 15:24 functools.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/functools.py
lrwxr-xr-x   1 hillma  eng     99 Dec  8 15:24 genericpath.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/genericpath.py
lrwxr-xr-x   1 hillma  eng     95 Dec  8 15:24 hashlib.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/hashlib.py
lrwxr-xr-x   1 hillma  eng     93 Dec  8 15:24 heapq.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/heapq.py
lrwxr-xr-x   1 hillma  eng     92 Dec  8 15:24 hmac.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/hmac.py
lrwxr-xr-x   1 hillma  eng     91 Dec  8 15:24 imp.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 importlib -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib
lrwxr-xr-x   1 hillma  eng     90 Dec  8 15:24 io.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/io.py
lrwxr-xr-x   1 hillma  eng     95 Dec  8 15:24 keyword.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/keyword.py
lrwxr-xr-x   1 hillma  eng     96 Dec  8 15:24 lib-dynload -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
lrwxr-xr-x   1 hillma  eng     97 Dec  8 15:24 linecache.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/linecache.py
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 locale.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py
-rw-r--r--   1 hillma  eng      0 Dec  8 15:24 no-global-site-packages.txt
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 ntpath.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ntpath.py
lrwxr-xr-x   1 hillma  eng     96 Dec  8 15:24 operator.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/operator.py
-rw-r--r--   1 hillma  eng     63 Dec  8 15:24 orig-prefix.txt
lrwxr-xr-x   1 hillma  eng     90 Dec  8 15:24 os.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py
lrwxr-xr-x   1 hillma  eng     97 Dec  8 15:24 posixpath.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 random.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py
lrwxr-xr-x   1 hillma  eng     90 Dec  8 15:24 re.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py
lrwxr-xr-x   1 hillma  eng    127 Dec  8 15:24 readline.so -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/readline.cpython-36m-darwin.so
lrwxr-xr-x   1 hillma  eng     95 Dec  8 15:24 reprlib.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/reprlib.py
lrwxr-xr-x   1 hillma  eng     99 Dec  8 15:24 rlcompleter.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/rlcompleter.py
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 shutil.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py
drwxr-xr-x  28 hillma  eng    952 May  1 10:40 site-packages
-rw-r--r--   1 hillma  eng  27639 May  1 10:40 site.py
lrwxr-xr-x   1 hillma  eng     99 Dec  8 15:24 sre_compile.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py
lrwxr-xr-x   1 hillma  eng    101 Dec  8 15:24 sre_constants.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_constants.py
lrwxr-xr-x   1 hillma  eng     97 Dec  8 15:24 sre_parse.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py
lrwxr-xr-x   1 hillma  eng     92 Dec  8 15:24 stat.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/stat.py
lrwxr-xr-x   1 hillma  eng     94 Dec  8 15:24 struct.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/struct.py
lrwxr-xr-x   1 hillma  eng     95 Dec  8 15:24 tarfile.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tarfile.py
lrwxr-xr-x   1 hillma  eng     96 Dec  8 15:24 tempfile.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tempfile.py
lrwxr-xr-x   1 hillma  eng     93 Dec  8 15:24 token.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/token.py
lrwxr-xr-x   1 hillma  eng     96 Dec  8 15:24 tokenize.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py
lrwxr-xr-x   1 hillma  eng     93 Dec  8 15:24 types.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/types.py
lrwxr-xr-x   1 hillma  eng     96 Dec  8 15:24 warnings.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/warnings.py
lrwxr-xr-x   1 hillma  eng     95 Dec  8 15:24 weakref.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/weakref.py
~$ cat /Users/hillma/homebrew/bin/http
#!/Users/hillma/homebrew/Cellar/httpie/0.9.9/libexec/bin/python3.6
# EASY-INSTALL-ENTRY-SCRIPT: 'httpie==0.9.9','console_scripts','http'
__requires__ = 'httpie==0.9.9'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('httpie==0.9.9', 'console_scripts', 'http')()
    )
~$ /Users/hillma/homebrew/Cellar/httpie/0.9.9/libexec/bin/python3.6 -c 'import sys; from pprint import pprint; pprint(sys.path); import enum; print(enum)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pprint'
```

**Comment by iansinnott** [comment]
Perhaps not ideal, but I was able to get it to work by bypassing brew all together and using the `pip` install instructions:

https://github.com/jakubroztocil/httpie#23windows-etc

**Comment by dwt** [comment]
I have the same problem, and there are lots of files missing in that libexec directory. Any workaround for this yet? Is this an error in the formula? (Probably)

**Comment by dwt** [comment]
After updating from Sierra to High-Sierra `brew reinstall httpie` fixed this - while this didn't work while I was still on Sierra. So this looks like a home-brew bug to me (but one I cannot recreate any more).

**Comment by xxKeith20xx** [comment]
Had the same issue on debian 10 - testing - ran a `sudo apt install --reinstall httpie` and saw it work fine after. 👍
