### ISSUE TITLE
Cannot send JSON Array of Numbers

### ISSUE THREAD

**Issue by webyneter** [jakubroztocil/httpie#636]
**What I'm trying to do**
Send a JSON array of numbers to a URL.

**What should happen**
The request should succeed.

**What's happenning instead**
The request yields
```shell
Traceback (most recent call last):
  File "/home/webyneter/.pyenv/versions/3.5.3/bin/http", line 11, in <module>
    sys.exit(main())
  File "/home/webyneter/.pyenv/versions/3.5.3/lib/python3.5/site-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/home/webyneter/.pyenv/versions/3.5.3/lib/python3.5/site-packages/httpie/core.py", line 210, in main
    parsed_args = parser.parse_args(args=args, env=env)
  File "/home/webyneter/.pyenv/versions/3.5.3/lib/python3.5/site-packages/httpie/input.py", line 151, in parse_args
    self._parse_items()
  File "/home/webyneter/.pyenv/versions/3.5.3/lib/python3.5/site-packages/httpie/input.py", line 355, in _parse_items
    data_class=ParamsDict if self.args.form else OrderedDict
  File "/home/webyneter/.pyenv/versions/3.5.3/lib/python3.5/site-packages/httpie/input.py", line 745, in parse_items
    data_class(data),
  File "/home/webyneter/.pyenv/versions/3.5.3/lib/python3.5/site-packages/httpie/input.py", line 635, in __setitem__
    assert not isinstance(value, list)
AssertionError
```

**Request** 
```shell
http -f POST <url> <headers> <param1>=<value1> <param2>@<value2> <param3>:=[1,2,3]
```
(Note that I'm sending the array via **`:=[1,2,3]`** as [by the docs](https://github.com/jakubroztocil/httpie#request-items).)

**Environment**
* Ubuntu 17.10
* Shell: `zsh`
* `http --version`: `0.9.9`
* `python --version`: `Python 3.5.3`

**Comment by webyneter** [comment]
I've found it working only when sending via `multipart/x-www-form-urlencoded`... obviously, well :)
