### ISSUE TITLE
Can't run httpie due to missing requests distribution - while present

### ISSUE THREAD

**Issue by cmhrpr** [jakubroztocil/httpie#658]
```
➜  ~ http httpie.org
Traceback (most recent call last):
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.12.3 (/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages), Requirement.parse('requests>=2.18.4'), {'httpie'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/http", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/Cellar/httpie/HEAD-0f4dce9_1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests>=2.18.4' distribution was not found and is required by httpie
```

Running Mac OS 10.13.3, Python 3.6.4 installed through homebrew. 

Requests 2.18.4 is installed:
`➜  ~ pip3 list  | grep requests
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
requests (2.18.4)
requests-file (1.4.2)`

**Comment by takeawaytrex** [comment]
I had originally installed through brew install httpie --HEAD, but removing the --HEAD flag fixed the problem.

Note that this required running brew unlink first.
