### ISSUE TITLE
Non user-friendly behavior (stacktrace dump) if config location isn't writable

### ISSUE THREAD

**Issue by AleksanderGrzybowski** [jakubroztocil/httpie#738]
Hello! Thanks for great tool.

I was trying to use httpie inside OpenShift pod, which underneath uses Docker containers without root privileges. Because there `HOME` is set to `/` by default, httpie crashes with permission error trying to create it's config dir, since regular user can't write to `/`.

This can be reproduced on Linux by overwriting `HOME` environment var with directory that current user can't write to:
```
$ HOME=/root http --debug google.com
Traceback (most recent call last):
  File "/usr/bin/http", line 11, in <module>
    load_entry_point('httpie==0.9.8', 'console_scripts', 'http')()
  File "/usr/lib/python3/dist-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/httpie/core.py", line 193, in main
    if env.config.default_options:
  File "/usr/lib/python3/dist-packages/httpie/context.py", line 82, in config
    self._config.save()
  File "/usr/lib/python3/dist-packages/httpie/config.py", line 68, in save
    with open(self.path, 'w') as f:
  File "/usr/lib/python3/dist-packages/httpie/config.py", line 34, in path
    os.makedirs(os.path.dirname(path), mode=0o700)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.httpie'

```

I checked what's inside httpie config directory after making some request once and I see only `config.json` with no custom options. I'd say it would be fine to skip writing this config file/dir if it is not possible, maybe with a warning? This would be more user-friendly than dying with a cryptic stacktrace. Or another option would be to catch this error and display some error message.

Please share your thoughts. Thanks again!

**Comment by jakubroztocil** [comment]
Fixed in `master`. Thanks
