### ISSUE TITLE
Brew version does not work for other users

### ISSUE THREAD

**Issue by nre-ableton** [jakubroztocil/httpie#742]
When attempting to use `httpie` as a user other than the one who manages the system's homebrew packages, there is a permission error which prevents this from working:

```
$ http
Traceback (most recent call last):
  File "/usr/local/bin/http", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    ws = cls()
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1968, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2038, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2495, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2870, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2459, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2649, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1414, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1410, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1522, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/idna-2.7-py3.7.egg-info/PKG-INFO'
```

Corresponding permissions for my system are like so:

```
$ id -u  # current user
502
$ gls -ldn /usr/local/Cellar  # user who owns brew's cellar
drwxrwxr-x 58 501 80 1856 Jan  8 17:50 /usr/local/Cellar
$ gls -ldn /usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/idna-2.7-py3.7.egg-info/PKG-INFO
-rwx------ 1 501 20 10565 Nov 24 15:40 /usr/local/Cellar/httpie/1.0.2/libexec/lib/python3.7/site-packages/idna-2.7-py3.7.egg-info/PKG-INFO
```

FWIW, I don't seem to have this problem with other Python brew executables.

**Comment by jakubroztocil** [comment]
Thanks for the report. It looks like the 2.7 idna package was shipped with the wrong permissions. 2.8 looks good:

```
/tmp $ ll idna-2.*
-rw-r--r--  1 jakub  wheel   169K  3 Feb 14:07 idna-2.7.tar.gz
-rw-r--r--  1 jakub  wheel   170K  3 Feb 14:09 idna-2.8.tar.gz

idna-2.7:
total 3736
-rwx------   1 jakub  wheel   3.9K 11 Jun  2018 HISTORY.rst
-rwx------   1 jakub  wheel   3.9K 11 Jun  2018 LICENSE.rst
-rwx------   1 jakub  wheel   127B 10 Jun  2018 MANIFEST.in
-rwx------   1 jakub  wheel    10K 11 Jun  2018 PKG-INFO
-rwx------   1 jakub  wheel   7.6K 10 Jun  2018 README.rst
drwxr-xr-x  14 jakub  wheel   448B  8 Jun  2017 chardet-3.0.4
-rw-r--r--   1 jakub  wheel   1.8M  3 Feb 14:07 chardet-3.0.4.tar.gz
drwx------  10 jakub  wheel   320B 11 Jun  2018 idna
drwx------   6 jakub  wheel   192B 11 Jun  2018 idna.egg-info
-rwx------   1 jakub  wheel   127B 11 Jun  2018 setup.cfg
-rwx------   1 jakub  wheel   2.0K 10 Jun  2018 setup.py
drwx------  10 jakub  wheel   320B 11 Jun  2018 tests
drwx------   4 jakub  wheel   128B 11 Jun  2018 tools

idna-2.8:
total 88
-rw-r--r--   1 jakub  wheel   4.0K  4 Dec 17:50 HISTORY.rst
-rw-r--r--   1 jakub  wheel   3.9K 11 Jun  2018 LICENSE.rst
-rw-r--r--   1 jakub  wheel   127B 27 Jan  2017 MANIFEST.in
-rw-r--r--   1 jakub  wheel    10K  4 Dec 18:11 PKG-INFO
-rw-r--r--   1 jakub  wheel   7.6K 11 Jun  2018 README.rst
drwxr-xr-x  10 jakub  wheel   320B  4 Dec 18:11 idna
drwxr-xr-x   6 jakub  wheel   192B  4 Dec 18:11 idna.egg-info
-rw-r--r--   1 jakub  wheel   127B  4 Dec 18:11 setup.cfg
-rw-r--r--   1 jakub  wheel   2.0K 11 Jun  2018 setup.py
drwxr-xr-x  10 jakub  wheel   320B  4 Dec 18:11 tests
drwxr-xr-x   4 jakub  wheel   128B  4 Dec 18:11 tools
```

I’ll update the Homebrew formula to refer to the latest version.

**Comment by jakubroztocil** [comment]
Fixed
