### ISSUE TITLE
Config.json updates cause parallel executiuon failures

### ISSUE THREAD

**Issue by jwgcooke** [jakubroztocil/httpie#788]
When running 2 scripts in separate terminals that make use of API calls I will periodically get an error caused by the config.json file being incorrectly formatted.  It would appear that one process is updating the file and the other process tries to read it in flight

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httpie/config.py", line 47, in load
    data = json.load(f)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/bin/http", line 11, in <module>
    load_entry_point('httpie==1.0.2', 'console_scripts', 'http')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httpie/core.py", line 193, in main
    if env.config.default_options:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httpie/context.py", line 84, in config
    self._config.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httpie/config.py", line 96, in load
    super(Config, self).load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httpie/config.py", line 51, in load
    (type(self).__name__, str(e), self.path)
ValueError: Invalid Config JSON: Expecting value: line 1 column 1 (char 0) [########/.httpie/config.json]

**Comment by adamchainz** [comment]
Same here, I can reliably replicate with GNU Parallel and a fast localhost server:

```
$ parallel -N0 http http://localhost:8000/ ::: {1..5}
Traceback (most recent call last):
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/site-packages/httpie/config.py", line 47, in load
    data = json.load(f)
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chainz/.pyenv/versions/3.7.5/bin/http", line 8, in <module>
    sys.exit(main())
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/site-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/site-packages/httpie/core.py", line 193, in main
    if env.config.default_options:
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/site-packages/httpie/context.py", line 84, in config
    self._config.load()
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/site-packages/httpie/config.py", line 96, in load
    super(Config, self).load()
  File "/Users/chainz/.pyenv/versions/3.7.5/lib/python3.7/site-packages/httpie/config.py", line 51, in load
    (type(self).__name__, str(e), self.path)
ValueError: Invalid Config JSON: Expecting value: line 1 column 1 (char 0) [/Users/chainz/.httpie/config.json]
Hello, World!Hello, World!Hello, World!Hello, World!%
```

**Comment by tedmiston** [comment]
I am hitting this one as well using multiple subprocesses programmatically.  Anyone have a recommended workaround?

**Comment by jakubroztocil** [comment]
Fixed in `master`, thanks!

**Comment by jwgcooke** [comment]
Is there a plan to release this or should I just build off of master?
