### ISSUE TITLE
http: error: ConnectionError: ('Connection aborted.', HTTPException('got more than 100 headers',)) while doing GET request to URL

### ISSUE THREAD

**Issue by spaceone** [jakubroztocil/httpie#802]
```
# http --debug --auth Administrator:password :/udm/ Accept:application/hal+json
HTTPie 0.9.8
Requests 2.12.4
Pygments 2.2.0
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516]
/usr/bin/python
Linux 4.9.0-9-amd64

<Environment {
    "colors": 8,
    "config": {
        "__meta__": {
            "about": "u'HTTPie configuration file'",
            "help": "u'https://httpie.org/docs#config'",
            "httpie": "u'0.9.8'"
        },
        "default_options": "[]"
    },
    "config_dir": "/root/.httpie",
    "is_windows": false,
    "stderr": "<open file '<stderr>', mode 'w' at 0x7f8eb13b51e0>",
    "stderr_isatty": true,
    "stdin": "<open file '<stdin>', mode 'r' at 0x7f8eb13b50c0>",
    "stdin_encoding": "UTF-8",
    "stdin_isatty": true,
    "stdout": "<open file '<stdout>', mode 'w' at 0x7f8eb13b5150>",
    "stdout_encoding": "UTF-8",
    "stdout_isatty": true
}>

>>> requests.request(**{
    "allow_redirects": false,
    "auth": "<httpie.plugins.builtin.HTTPBasicAuth object at 0x7f8eaf02b4d0>",
    "cert": "None",
    "data": {},
    "files": {},
    "headers": {
        "Accept": "application/hal+json",
        "User-Agent": "HTTPie/0.9.8"
    },
    "method": "get",
    "params": {},
    "proxies": {},
    "stream": true,
    "timeout": 30,
    "url": "u'http://localhost/udm/'",
    "verify": true
})


http: error: ConnectionError: ('Connection aborted.', HTTPException('got more than 100 headers',)) while doing GET request to URL: http://localhost/udm/
Traceback (most recent call last):
  File "/usr/bin/http", line 11, in <module>
    load_entry_point('httpie==0.9.8', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/dist-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/httpie/core.py", line 227, in main
    log_error=log_error,
  File "/usr/lib/python2.7/dist-packages/httpie/core.py", line 99, in program
    final_response = get_response(args, config_dir=env.config.directory)
  File "/usr/lib/python2.7/dist-packages/httpie/client.py", line 70, in get_response
    response = requests_session.request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', HTTPException('got more than 100 headers',))
```

httpie is not usable for applications which use a lot of HTTP headers (e.g. the `Link` http header).

**Comment by jakubroztocil** [comment]
Thanks for the report. This is fixed in `master`. https://github.com/jakubroztocil/httpie/blob/master/CHANGELOG.rst

**Comment by spaceone** [comment]
Thank you! :-)
