### ISSUE TITLE
Stack trace when trying to issue POST request with list

### ISSUE THREAD

**Issue by bredmor** [jakubroztocil/httpie#844]
Any POST request containing an array/list causes a stack trace and exit for me on Ubuntu 19.10

Ex:
```
http POST localhost/test_endpoint answer:='["Red","Yellow"]'
Traceback (most recent call last):
  File "/usr/bin/http", line 11, in <module>
    load_entry_point('httpie==0.9.8', 'console_scripts', 'http')()
  File "/usr/lib/python3/dist-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/httpie/core.py", line 210, in main
    parsed_args = parser.parse_args(args=args, env=env)
  File "/usr/lib/python3/dist-packages/httpie/input.py", line 151, in parse_args
    self._parse_items()
  File "/usr/lib/python3/dist-packages/httpie/input.py", line 355, in _parse_items
    data_class=ParamsDict if self.args.form else OrderedDict
  File "/usr/lib/python3/dist-packages/httpie/input.py", line 745, in parse_items
    data_class(data),
  File "/usr/lib/python3/dist-packages/httpie/input.py", line 635, in __setitem__
    assert not isinstance(value, list)
AssertionError
```

I'm not sure exactly what's going on, but judging from similar errors in this repo and the context of the functions being called, I'd venture a guess that the package is trying to write to something  outside my home directory, which it does not have access to. 

If this is correct, and whatever it's trying to write to is intended to be ephemeral, may I suggest using $TMPDIR for this purpose on POSIX-compliant systems.

**Comment by jakubroztocil** [comment]
@bredmor your httpie version is very old, please upgrade to v2.0.0. There you example works:

```bash
$ http --offline POST localhost/test_endpoint answer:='["Red","Yellow"]'
```

```http
POST /test_endpoint HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 29
Content-Type: application/json
Host: localhost
User-Agent: HTTPie/2.0.0

{
    "answer": [
        "Red",
        "Yellow"
    ]
}
````
