### ISSUE TITLE
http: error: ClassNotFound: no lexer for alias 'json' found

### ISSUE THREAD

**Issue by gawi** [jakubroztocil/httpie#848]
```
$ http --traceback --all --json get http://localhost/a.json
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Length: 9
Content-Type: application/json
Date: Thu, 06 Feb 2020 18:18:34 GMT
ETag: "9-59dec3f8470cd"
Keep-Alive: timeout=5, max=100
Last-Modified: Thu, 06 Feb 2020 18:14:47 GMT
Server: Apache/2.4.6 (CentOS)


http: error: ClassNotFound: no lexer for alias 'json' found
Traceback (most recent call last):
  File "/usr/bin/http", line 9, in <module>
    load_entry_point('httpie==0.9.4', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/site-packages/httpie/core.py", line 227, in main
    log_error=log_error,
  File "/usr/lib/python2.7/site-packages/httpie/core.py", line 138, in program
    write_stream(**write_stream_kwargs)
  File "/usr/lib/python2.7/site-packages/httpie/output/streams.py", line 35, in write_stream
    for chunk in stream:
  File "/usr/lib/python2.7/site-packages/httpie/output/streams.py", line 161, in __iter__
    for chunk in self.iter_body():
  File "/usr/lib/python2.7/site-packages/httpie/output/streams.py", line 297, in iter_body
    yield self.process_body(body)
  File "/usr/lib/python2.7/site-packages/httpie/output/streams.py", line 267, in process_body
    chunk = self.formatting.format_body(content=chunk, mime=self.mime)
  File "/usr/lib/python2.7/site-packages/httpie/output/processing.py", line 49, in format_body
    content = p.format_body(content, mime)
  File "/usr/lib/python2.7/site-packages/httpie/output/formatters/colors.py", line 64, in format_body
    lexer = self.get_lexer(mime, body)
  File "/usr/lib/python2.7/site-packages/httpie/output/formatters/colors.py", line 73, in get_lexer
    body=body,
  File "/usr/lib/python2.7/site-packages/httpie/output/formatters/colors.py", line 119, in get_lexer
    lexer = pygments.lexers.get_lexer_by_name('json')
  File "/usr/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 80, in get_lexer_by_name
    raise ClassNotFound('no lexer for alias %r found' % _alias)
pygments.util.ClassNotFound: no lexer for alias 'json' found
```

With `--pretty=none`:

```
$ http --pretty=none --all --json get http://localhost/a.json
HTTP/1.1 200 OK
Date: Thu, 06 Feb 2020 18:16:25 GMT
Server: Apache/2.4.6 (CentOS)
Last-Modified: Thu, 06 Feb 2020 18:14:47 GMT
ETag: "9-59dec3f8470cd"
Accept-Ranges: bytes
Content-Length: 9
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json

{"a":23}
```
Additional info:
```
$ http --version
0.9.4
```

```
$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```

```
$ rpm -qa | grep httpie
python2-httpie-0.9.4-1.el7.noarch
```

```
$yum -C list python2-httpie
Installed Packages
python2-httpie.noarch    0.9.4-1.el7 @epel
```

NOTE:  epel = Extra Packages for Enterprise Linux 7 - x86_64

```
$ rpm -qf /usr/lib/python2.7/site-packages/pygments/
python-pygments-1.4-10.el7.noarch
```

**Comment by gawi** [comment]
To try it from docker:

$ **docker run --rm -it centos:7**

[root@98afac715b08 /]# **yum -y -q install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum -y -q install httpie httpd**
[root@98afac715b08 /]# **/usr/sbin/httpd**
[root@98afac715b08 /]# **echo "{}" > /var/www/html/a.json**
[root@98afac715b08 /]# **http --json http://localhost/a.json**
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Length: 3
Content-Type: application/json
Date: Thu, 06 Feb 2020 21:44:24 GMT
ETag: "3-59def2ce1359a"
Keep-Alive: timeout=5, max=100
Last-Modified: Thu, 06 Feb 2020 21:44:19 GMT
Server: Apache/2.4.6 (CentOS)


http: error: ClassNotFound: no lexer for alias 'json' found

**Comment by jakubroztocil** [comment]
@gawi thanks for the report. That HTTPie version is very old. Please try it with the latest one, and reopen if the problem persists.
