### ISSUE TITLE
Can't run simple http get from shell script

### ISSUE THREAD

**Issue by lbindal** [jakubroztocil/httpie#916]
Very simple Httpie Command: "http GET https://reqres.in/api/users?page=2"
This is working link..just put in browser and get result
https://reqres.in/api/users?page=2

created a shell script called httpieshell.sh
httpieshell.sh contains "http GET https://reqres.in/api/users?page=2" (Without quotes)
from my windows on which i have installed ubuntu and using "ConEmu" to run my http command
when i run command "http GET https://reqres.in/api/users?page=2" directly from ConEmu it works fine
When i put it in shell file and do

sh httpieshell.sh

it complains this problem

Traceback (most recent call last):
  File "/home/maverick/.local/bin/http", line 11, in <module>
    sys.exit(main())
  File "/home/maverick/.local/lib/python2.7/site-packages/httpie/__main__.py", line 10, in main
    from .core import main
  File "/home/maverick/.local/lib/python2.7/site-packages/httpie/core.py", line 21
    args: List[Union[str, bytes]] = sys.argv,
        ^
SyntaxError: invalid syntax

**Comment by lbindal** [comment]
This issue is resolved. Python version 3.8 worked for me 

import os
import sys
os.system(finalHttpieCommand)
